### ISSUE TITLE
Easy to use dataset for DALL-E

### ISSUE THREAD

**Issue by mrconter1** [EleutherAI/DALLE-mtf#4]
The [COCO dataset](https://cocodataset.org/#overview) is a high-quality dataset both in terms of images and text. Each image has multiple captions and it consists of around 100 000 images. I have created a [Google Colab](https://colab.research.google.com/drive/1KxG1iGBoKt2fLVH7uXG_vhvll2OlFkey?usp=sharing) which does the following:

1. Fetches the COCO images and captions
2. Allows the user to specify image dimensions which the images will be resized to
3. Stores information in two files for easy access in the following format:

_od-captions.txt_ (<image_path> : <image_caption>)
> train2017/000000203564.jpg : A bicycle replica with a clock as the front wheel.
train2017/000000322141.jpg : A room with blue walls and a white sink and door.
train2017/00000016977.jpg : A car that seems to be parked illegally behind a legally parked car
train2017/000000106140.jpg : A large passenger airplane flying through the air.
train2017/000000571635.jpg : A bathroom with a toilet, sink, and shower.

_od-captionsonly.txt_ (<image_caption>)
> A bicycle replica with a clock as the front wheel.
A room with blue walls and a white sink and door.
A car that seems to be parked illegally behind a legally parked car
A large passenger airplane flying through the air.
A bathroom with a toilet, sink, and shower.

Here is an example image and caption:
![image](https://user-images.githubusercontent.com/32551374/104190487-76918d80-541c-11eb-9b8c-a312475100d1.png)
_The man at bat readies to swing at the pitch while the umpire looks on._

I have written this hoping it will be somewhat compatible with @htoyryla's [fork](https://github.com/htoyryla/DALLE-pytorch) of a similar project. Might be of interest to you. Feel free to use this to generate a dataset for DALL-E!

**Comment by StellaAthena** [comment]
This looks awesome! Thanks for the contribution 😄. Would you mind modifying the code (or adding a second function) to process the data in the way described in the README? Namely

> Custom datasets should be formatted in a folder, with a jsonl file in the root folder containing caption data and paths to the respective images, as follows:
> 
> Folder structure:
> 
>         data_folder
>             jsonl_file
>             folder_1
>                 img1
>                 img2
>                 ...
>             folder_2
>                 img1
>                 img2
>                 ...
>             ...
> 
> jsonl structure:
>     {"image_path": folder_1/img1, "caption": "some words"}
>     {"image_path": folder_2/img2, "caption": "more words"}
>     ...
> you can then use the create_paired_dataset function in src/data/create_tfrecords.py to encode the dataset into tfrecords for use in training.

**Comment by sdtblck** [comment]
Hey @StellaAthena @mrconter1 ! 
We actually already have a script for coco. Dataset collection will be happening in a separate repo, though (which is private for now until we make some progress :)
